import { CLIENT_STATIC_FILES_PATH } from 'next/dist/shared/lib/constants'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAuth } from '../hooks/useAuth'


export default function Home() {
  
  const {user, logIn, logOut} = useAuth(); 

  console.log('user is', user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Lay Down</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {! user && (
        <p>
          <button onClick={logIn}>Log In</button>
       </p>
      )}

      { user && (
        <p>
          <button onClick={logOut}>Log Out</button>
       </p>
      )}



      <main className={styles.main}>
        <h1 className={styles.title}>
          Lay Down
        </h1>

        <p className={styles.description}>
         Embrace your Talent
        </p>

        <div className={styles.row}>
          <div className={styles.column}>
            <div className={styles.columncontent}>
            <h1 className={styles.examplename}>
              First go at Producing
            </h1>
            <h2 className={styles.examplegenre}>
              Pop
            </h2>
            <p className={styles.exampledetails}>
              Looking for a hard synth bass line to go with this beat I made.
            </p>
            <div className={styles.examplepost}>
                <audio controls>
                  <source src="public/Crazy.mp3" type="audio/mp3"></source>
                </audio>
                </div>

                <a href="api/other.js">Hear other users recordings</a>
              </div>
            </div>
          <div className={styles.column}>
            <div className={styles.columncontent}>
            <h1>
                I am recording and submitting things
              </h1>
              <form>
              <label for="fileToUpload">Insert audio file</label><br />
                <input type="file" name="fileToUpload" accept=".mp3,audio/*" /><br />
                <label for="Text1">Type a short description</label>
                <textarea name="Text1" cols="40" rows="5"></textarea><br />

                <input type="submit" />
                
              </form>
              </div>
            </div>
          </div>
      </main>
    </div>
  )
}
